### ISSUE TITLE
Customer Support Tracking

### ISSUE THREAD

**Issue by stevebrownlee** [handy-pandas/bangazon_orientation_api#18]
## Feature Description

The database, and API need to be updated to allow us to handle customer support issues.

1. Employees must be able to be designated as customer support specialists
1. Customer support issues must be stored in database
    1. Customer identifier
    1. Ticket description
    1. Order identifier
    1. Date ticket created
    1. Resolution description
    1. Date ticket resolved
1. Expose all support tickets as a resource via the API

### Adding issue template for this ticket.
1. Product Ticket Title: Customer Support Tracking
2. Proposed Feature Title: Expose the customer support tickets to the API
3. Description of the feature: See above from product owner
 * What: add support ticket table and expose to the API
 * Where (when the feature would show up): Exposed to the API
 * How (what implentation is needed): Create table for support ticket.
4. What files will be created or edited (where, file path): create data file supportticket.json, models.py, serialization.py, views.py, urls.py, alter damnit_django shell file to add data.
5. Potential Impact on the Project (possible conflicts with other features, hierarchy of feature completion): None
6. Estimated time of completion: 2 hours
7. Actual time of completion (added as a comment when moved to Done column):

**Comment by jamestonkin** [comment]
Updated ticket with our issue template.
