### ISSUE TITLE
Expose our Product Categories/Types to the API 

### ISSUE THREAD

**Issue by talbotlawrence** [handy-pandas/bangazon_orientation_api#2]
# Issue Template for Bangazon Orientation API

1. Product Ticket Title:  Orientation API
2. Proposed Feature Title:  Create a Product Category SQL table
3. Description of the feature:  
 * What:  Create a Product Category table with the CategoryId primary key and the Name column.
 * Where (when the feature would show up):  This table will be exposed to the API.
 * How (what implementation is needed):  I will create a class in the model.
4. What files will be created or edited (where, file path):  orientationapi/models/productcategory.py, orientationapi/serializers.py, orientationapi/views.py, bangazon/urls.py
5. Potential Impact on the Project (possible conflicts with other features, hierarchy of feature completion):  None
6. Estimated time of completion:  15 minutes
7. Actual time of completion (added when moved to Done column):

**Comment by taylorperkins** [comment]
Good job

**Comment by jamestonkin** [comment]
Actual time of completion (added when moved to Done column): 2 hours
