### ISSUE TITLE
Expose Employees to API

### ISSUE THREAD

**Issue by barfootaaron** [handy-pandas/bangazon_orientation_api#6]
# Issue Template for Bangazon Orientation API

1. Product Ticket Title:
Create Employee Table

2. Proposed Feature Title:
Employee Table

3. Description of the feature:
 * What: Table containing employee-specific data (fn, ln, jobTitle) along with foreign key for DepartmentId
 * Why: Store data for each employee

4. What files will be created or edited (where, file path): 
Create bangazon/models/employee.py
Edit bangazon/serializers.py
Edit bangazon/views.py
Edit bangazon/urls.py

5. Potential Impact on the Project (possible conflicts with other features, hierarchy of feature completion): None

6. Estimated time of completion: 30 mins

7. Actual time of completion (added when moved to Done column):

**Comment by jamestonkin** [comment]
Tested that the employee table is exposed to the API. It is! :shipit:
