### ISSUE TITLE
Expose our Customer information to the API

### ISSUE THREAD

**Issue by talbotlawrence** [handy-pandas/bangazon_orientation_api#7]
# Issue Template for Bangazon Orientation API

1. Product Ticket Title:  Orientation API
2. Proposed Feature Title:  Create a Customer SQL table
3. Description of the feature:  
 * What:  Create a Customer table with the CustomerId primary key, the FirstName column, the LastName column, the JoinDate column, the InactiveDate column, and Inactive column (boolean--True or False).
 * Where (when the feature would show up):  This table will be exposed to the API.
 * How (what implementation is needed):  I will create a class in the model.
4. What files will be created or edited (where, file path):  orientationapi/models/customer.py, orientationapi/serializers.py, orientationapi/views.py, bangazon/urls.py
5. Potential Impact on the Project (possible conflicts with other features, hierarchy of feature completion):  None
6. Estimated time of completion:  15 minutes
7. Actual time of completion (added when moved to Done column):

**Comment by taylorperkins** [comment]
Add in the PR `python manage.py makemigrations` so I know exactly how to run this. Also link up the url path within the PR so I can just copy and paste. Otherwise, all functionality is great:)
