### ISSUE TITLE
Expose Training Programs to API

### ISSUE THREAD

**Issue by barfootaaron** [handy-pandas/bangazon_orientation_api#9]
# Issue Template for Bangazon Orientation API

1. Product Ticket Title:
Create Training table

2. Proposed Feature Title:
Training table

3. Description of the feature:
 * What: Table containing Training Program data (title, startDate, endDate, maxAttendance)
 * Why: Store data for each Training Program

4. What files will be created or edited (where, file path):
Create bangazon/models/training.py
Edit bangazon/serializers.py
Edit bangazon/views.py
Edit bangazon/urls.py

5. Potential Impact on the Project (possible conflicts with other features, hierarchy of feature completion):
If Employee table has been completed, create a JOIN table between the Employee and Training tables named EmployeeTraining. This will be created the same way that the Employee and Training tables were created.

6. Estimated time of completion: 30 mins

7. Actual time of completion (added as a comment when moved to Done column):

**Comment by jamestonkin** [comment]
Tested to see if training programs are exposed to the API. It is. :shipit:

**Comment by jamestonkin** [comment]
Tested to see if training programs are exposed to the API. It is. :shipit:

**Comment by taylorperkins** [comment]
cool. Just pulled it down and checkout it out. Looks good
